---
_extends: .github

repository:
  name: hs-github-tools
  description: Small GitHub utilities like pull-status and changelog generator
  topics: github, haskell
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "bazel-release"
          - "build / cabal"
          - "build / stack"
          - "code-review/reviewable"
