---
_extends: template

repository:
  name: hs-github-tools
  description: Small GitHub utilities like pull-status and changelog generator
  topics: github, haskell
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - Travis CI - Pull Request
          - WIP
          - code-review/reviewable
          - license/cla
