---
_extends: .github

repository:
  name: hs-github-tools
  description: Small GitHub utilities like pull-status and changelog generator
  topics: github, haskell
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "cirrus-ci"
          - "Codacy Static Code Analysis"
          - "code-review/reviewable"
