---
language: generic
dist: xenial
os: linux

env:
  global:
    # HACKAGE_USERNAME=[secure]
    - secure: "C9c+Zf4yOTd7hL/no4y1WLs81unoo4j72qiO//pCNteiqK5DSHXeDdzRpolC2kPhPjKuS0Sw0fy/MoMDsaIiv/p/Cl+NyJLisKKn/VtYhFKIHh3ctgYkcQkddvaMwxkJxyq2xMHSr+VWSIzPdbH/r6H0pRcn8a4zcRKnbj2t12tcSEKVgZyi8pai1t8nuUJY57rvrvUtDtpExATAqn8rUHbAu8+lOwgMQgJlP3c7mz3ZZcSVf82fFtb6Z+BRBdV4TImq9pQOGzDcz79h0dvPeML/fUUHa1hSHKF7T+4yr3UXyYafJ8TojfiwalBmReiKRnAqa6Vp6JTM4wVfGj7Z1gJJ4YQFLFi8ZRhHsBxtF4JKuoV12SBFmeYMC2qmXjZKn1vOyfy1pY6yhk14saBZtZrxvxgdOjSEpukjqbne3q0ckMNVM9DxmILPvL4YUR8ayVvDMob97z43CVxEHKnCDloSkS6IH08v1P4SN3GXCEqo5eDQV+XvAXWby9MF7CU8Mp1HhUh/xX3pOs9RKqfvJ0MRW+j5MRP3a1fegpPntPn/M+L3/eqlGFcYhttpCxik2sfePeunh2xUGqVCN8JNvlIC3yLKgFTbdd8Tx/taTj2+ZlqnLdru1Rkcmelgj1O8eMtMh0/NP/ZsO/YfH2GYBcoPsZqpdFA01ZajonzOytA="
    # HACKAGE_PASSWORD=[secure]
    - secure: "KaSOcPujaJbGSY1/41vyaRCw2/bCUF021kO7nTVpO2lkwymJYgbcFuskBZC8JQN5NqiXrIgb0XM/N57l0/wNs+gyjDt7NWSF4OPxebiDxRN4BSejesiWXMafKthIlXn8lwhhAL7EYPGQ5ei/VwJUlClcOXGR08UxS1ePeABKzOX3qJZLCZf/9KmLm4k+GA2YXRCdA7BnQs7OtLg09lJ1EirZFBGCtak6xZ2FJqAXMimkdbAQMJrCIupPtr7sj2lnxACLc7G+JDqfGoqcpR0T6uV40pP90LGH+SLDzw3xCpnnqHNFC0RvcbgOHGWCPiSfowavbS0o+VPHAlXBOd7jgUaU0fys2AeTiWIyOnAvhQi3zv1PWx+CbCUxcx47wCAX6bMAkD4TG1RH2RxZWAZJIVyzA90RCmJL3I3AKh06F4wHzuqS91bcK0L5j7oTr3nhq82qFRxz58hNQKutSVWbdwE7BF2mlW8YXNRDSv84LQQkq8lqYU/5AAVXtj5p68+F6B0yOW2t9DE5zVHX1PATefNJjZ58prS6dbilTPSsNHsiDh3pheFfrhHIi7A4duPIHqXkjJKcZJ+KBgoZXAVnIERe+Hpe4AorPpeZ+FM6u4NvfAikiZryZoTh8sDVuVBIQNhE7OX1zn0uuDArlDugNMDcWPSOs5AuM73kP9Si9Hg="

cache:
  timeout: 600
  directories:
    - $HOME/.local
    - $HOME/.stack

script:
  - bash <(travis_retry curl -s https://raw.githubusercontent.com/TokTok/hs-tools/master/bin/travis-haskell) script
  - eval $(travis-haskell env)

deploy:
  provider: releases
  token:
    secure: "LpUAYk3pSGlTjakhkh/TzQTDCYj3upRlmEgq5VjyiM6Gsx+GybnQbrBDC2GBF7zOERkx535O0CBf4b7hvXJxNEVAjX5tGemqn8772xAbzAeVQogVUNc+WXRP7eBtcwhy8c/uC2iTHODAgfjOWqYZkyHcq8gMVON0JPgxQoGnue1KtItNlYOtEJgTfbsIW3bI1oACfyejmXIvpEGuuP/C282apMmLkkJGBZ45/YRJOXLqai6sWD9Zv7fIb5lfdlF0xA9waYcmRVgqYd9cAgOV++P9Rxs5s1rr9Qvmdqx71w4RhPQ2nXheF7zJMPBrA1dCVT5gRxxuNsMg8LJcyuGJZYg+XEQWiKk//G4vsVMgoXv87Quh3CfmHEcotQSKW5vbj/mKSa6fOhiEXLTxcrVE/X8CmV6ytlw1ZEt1CD8xIX1P7YGafSQmS4/3/I1D9VLUhHpFIaUZAtVtgX72lTIpj+oshwKoJk79skK6OEVST6XNi7MVpuBi30DmF7M8xvmT7cha3K6KVXZrhx8GkYxtjqFgDAozB2XI+Sd3VXJudNwLHI4m9HfRXLAezDkRBJGYOckEMyEiZLc7gV5175QbIsbInSxtO7fGFHIAUTM+ygCVxsfpzdb39bBZKY7w+Oe2NxupvHyvBmcQ7ZNRYq/1Yw07e2dK0XCKYRLvEouoU8I="
  file: $PACKAGE-$VERSION.tar.gz
  skip_cleanup: true
  on:
    repo: TokTok/hs-github-tools
    tags: true

after_deploy: travis-haskell deploy

# Only build pull requests and releases, don't build master on pushes,
# except through api or cron.
if: type IN (pull_request, api, cron) OR tag IS present
