---
packages: [.]
resolver: lts-6.27
extra-deps:
  - HUnit-1.6.0.0
  - QuickCheck-2.11.3
  - aeson-1.4.0.0
  - aeson-compat-0.3.8
  - attoparsec-0.13.2.2
  - attoparsec-iso8601-1.0.0.0
  - base-compat-0.10.4
  - base-orphans-0.5.4
  - bifunctors-5.5.3
  - binary-orphans-0.1.8.0
  - bsb-http-chunked-0.0.0.2
  - bytestring-builder-0.10.8.1.0
  - cabal-doctest-1.0.6
  - case-insensitive-1.2.0.11
  - cpphs-1.20.8
  - exceptions-0.8.3
  - fast-logger-2.4.11
  - github-0.19
  - hspec-2.5.5
  - hspec-core-2.5.5
  - hspec-discover-2.5.5
  - hspec-expectations-0.8.2
  - http-api-data-0.3.8.1
  - http-media-0.7.1.2
  - http-types-0.12.1
  - mmorph-1.1.2
  - natural-transformation-0.4
  - network-2.7.0.2
  - parsec-3.1.13.0
  - quickcheck-io-0.2.0
  - resourcet-1.1.11
  - safe-0.3.17
  - semigroupoids-5.2.1
  - semigroups-0.18.5
  - servant-0.13.0.1
  - servant-server-0.13.0.1
  - singleton-bool-0.1.4
  - split-0.2.3.3
  - string-conversions-0.4.0.1
  - tagged-0.8.6
  - text-1.2.3.0
  - th-abstraction-0.2.8.0
  - transformers-compat-0.5.1.4
  - unix-compat-0.5.0.1
  - unix-time-0.3.8
  - unliftio-core-0.1.1.0
  - vault-0.3.1.1
  - vector-binary-instances-0.2.4
  - vector-instances-3.4
  - wai-extra-3.0.22.0
  - warp-3.2.23
  - word8-0.1.3
